### ISSUE TITLE
Error in the localised Italian labels of the Spatial Scope Register items in the SKOS/RDF file 

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-registry#1]
The labels of the [Spatial Scope Register](https://inspire.ec.europa.eu/metadata-codelist/SpatialScope) items localised in Italian language in the [SKOS/RDF file](https://inspire.ec.europa.eu/registry/res/custompages/SpatialScope.rdf) are not proper as they don't align with those ones defined in the register.

Specifically:
- the label "Regionale" in the register becomes "Regionali" in the SKOS/RDF file;
- the label "Nazionale" in the register becomes "Nazionali" in the SKOS/RDF file;
- the label "Europeo" in the register becomes "Europea" in the SKOS/RDF file;
- the label "Locale" in the register becomes "Locali" in the SKOS/RDF file.

As the SKOS/RDF file is used in GeoNetwork, the risk, already experienced, is to generate metadata records with errors in the keywords for spatial scope.

**Comment by df-git** [comment]
Dear @AntoRot ,
Thank you for your feedback.
The problem has been resolved.
Best regards

**Comment by AntoRot** [comment]
Dear @df-git,

Thank you very much!

Best regards.
