### ISSUE TITLE
Please consider to re-open the issue related to harmonised layer names, prematurely closed

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-registry#10]
Please consider to re-open the prematurely closed incident https://github.com/INSPIRE-MIF/helpdesk-registry/issues/5 as the layer names are actually listed in the Comission Regulation 1089/2010 which is refered in the answer to the incident.

Those layers are not new layer names, but are layers whose names are derived from the Code Lists provided in the Comission Regulation 1089/2010, starting with section 9.4. For some data themes layer names is complete, but for other data themes, including for the Protected Sites the layer names is incomplete in the INSPIRE Registry. It can be easily spotted by comparing the number of layers for different data themes in the INSPIRE Registry, at https://inspire.ec.europa.eu/layer. To provide only one example, for Soil (SO) were added 38 layer names, while for Protected Sites (PS) was added only one  even if other 26 more layer names should be included in the INSPIRE Registry according to the Commision Regulation.

**Comment by hernlor** [comment]
Dear @iuriemaxim , what you say is completely right. I swapped the "code list" registers with the "layers" one.  I will amend it. Thanks for pointing out.

What I wanted to say is that the layer register "contains all the harmonised layer, as defined in the COMMISSION REGULATION (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services together with its amendments. "

In the above-mentioned regulation, in section "9.5. Layers" , only one layer is listed: **PS.ProtectedSite**

![image](https://user-images.githubusercontent.com/80747974/112514063-385a0800-8d95-11eb-96f9-4294b8939336.png)

There can be differences with the technical guidelines, however to take any decision it should be first requested by your corresponding submitting organisation as explained in the other thread.

I hope this clarifies.

Kind regards, 
The INSPIRE registry team

**Comment by iuriemaxim** [comment]
@hernlor Probably it is a difference on how the Commision Regulation was treated/updated for different Annexes of the Directive. As the Annex I was firstly covered by the Regulation 1089/2010, probably not all the layers were included. However as the Regulation is listing the code lists in section 9.4, it means that a data provider will create features that corespond to those code lists, which means that they should be represented as well in view services. So technically those layers will exist in the view services.

That's why in the Technical Guidelines these layers are listed as being optional, as not all Member States will have all those protected areas categories as differences exist between the countries.

Now as data providers created the features in the spatial data set and as the view services are created based on those features, the INSPIRE validator triggers an error because it looks at the list of harmonised layers that are listed in the INSPIRE Registry.

You may see one incident mentioned here https://github.com/INSPIRE-MIF/helpdesk-validator/issues/491

So we are now moving in circles as the people that are taking care of the development of the validator are saing that the INSPIRe Registry should list those layers as they are in the TG, while from the INSPIRE Registry your message is to to submit this trough the coresponding submitting organisation,

However this is not something to be comunicated by a Member State, as the incident is between various components of the INSPIRE infrastructure which are managed by the Commision, namely by the INSPIRE Registry and the INSPIRE Validator,

Therefore I would kindly ask you to discuss with the coleagues that are developing/maintaining/supervising the INSPIRE Validator and to fix this issue in such a way that Member States not to receive errors when they are creating services that are INSPIRE compliant according to all these documents: INSPIRE Directive, Commision Regulation and Technical Guidelines.

Technically it is not possible to create a dataset which have features as described in section 9.3 of the Commision Regulation without creating view services for them. Therefore harmonised layer names should exist for all features that are coresponding to code list registry values that are present in the section 9.3 of the Commsion Regulation.

Please leave this incident opened until it will be fixed either in the INSPIRE Registry, either in the INSPIRE Validator.

**Comment by iuriemaxim** [comment]
The alternative of not having (all/enough) harmonised layer names, is described in this incident https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39 where it is proposed to be able to provide any name for a layer and subsequently, both the Layer section and the Code Lists will ne useless. I think that it is important to be clear for the data providers, what they need to do, from both sides, the INSPIRE Validator and the INSPIRE Registry, altrough the INSPIRE Directive is quite clear in this respect, but the components of the INSPIRE infrastructure creates confusion.

**Comment by arantzaetxebarria** [comment]
Dear  @iuriemaxim 

Thanks for your comments, what @hernlor said [here ](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/10#issuecomment-807115730)about the PS layers is correct, the INSPIRE Registry only "contains all the harmonised layer, as defined in the COMMISSION REGULATION (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services together with its amendments. " ([consolidated document](https://eur-lex.europa.eu/eli/reg/2010/1089))

However, for other themes like NZ in [issue28](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/28) we will proceed to analyse and add the missing layers referenced in the consolidated document.

Best regards
