### ISSUE TITLE
Cannot open & download the Inspire 1 km^2 grid data 

### ISSUE THREAD

**Issue by ayschaef** [INSPIRE-MIF/helpdesk-registry#104]
Please replace these lines with a brief summary of your issue/question. Remember to specify all the required information in order to facilitate the understanding of the issue.

To help us investigate the issue, you may want to include:

- a description of the steps to reproduce your issue
- the browser and version used
- a screenshot illustrating the problem
- the URI of the reference code or the URL of the page

**Comment by arantzaetxebarria** [comment]
It seems that the issue has been opened by mistake.
@ayschaef  If you have any questions, please do not hesitate to contact us again.

Best regards
