### ISSUE TITLE
Incorrect link in the Registry ".../ProtectedLandscapeOrSeascape" instead of "../protectedLandscapeOrSeascape"

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-registry#11]
The following link in the Registry https://inspire.ec.europa.eu/codelist/IUCNDesignationValue/ProtectedLandscapeOrSeascape is incorrect, as the first character should not be a capital leter, so the correct registry value should be
https://inspire.ec.europa.eu/codelist/IUCNDesignationValue/protectedLandscapeOrSeascape
Protected -> protected.

This error in the INSPIRE Registry is impacting the correct validation in the INSPIRE Validator as mentioned also in the prematurely closed incident https://github.com/INSPIRE-MIF/helpdesk-registry/issues/5

**Comment by hernlor** [comment]
Dear @iuriemaxim, thank you for your patience.

The code list value has been corrected as notified.
The valid URI is: https://inspire.ec.europa.eu/codelist/IUCNDesignationValue/protectedLandscapeOrSeascape

Please, remind that changes impacting the content can only be proposed the appointed organisations.
https://github.com/INSPIRE-MIF/helpdesk-registry/blob/main/submitting-organisations-list.md

Kind regards, 
INSPIRE Registry team

**Comment by iuriemaxim** [comment]
@hernlor Thank you for correcting the INSPIRE Registry.
