### ISSUE TITLE
Several Survey Type labels not matching their definition

### ISSUE THREAD

**Issue by lvdbrink** [INSPIRE-MIF/helpdesk-registry#14]
URI of the register/reference code: URI http://inspire.ec.europa.eu/codelist/SurveyTypeValue

Overall motivation: Several items from the SurveyTypeValue list have definitions that do not match their label. The expert that brought this to my attention suggests the invalidation of these items. Perhaps they could also be corrected in some way, it is not immediately clear to me which is best.

The individual motivation and proposed change per item:

Motivation: The definition of the value airborne geophysical survey does not match with the label and description
Proposed change: Invalidate the value airborne geophysical survey  
Change type: Invalidation

Motivation: The definition of the value ground gravity survey does not match with the label and description
Proposed change: Invalidate the value ground gravity survey
Change type: Invalidation

Motivation: The definition of the value 3D resistivity survey does not match with the label and description
Proposed change: Invalidate the value 3D resistivity survey 
Change type: Invalidation

Motivation: The definition of the value seismological survey does not match with the label and description
Proposed change: Invalidate the value seismological survey
Change type: Invalidation

Motivation: The definition of the value 2D seismic survey does not match with the label and description
Proposed change: Invalidate the value 2D seismic survey 
Change type: Invalidation

Motivation: The definition of the value 3D seismic survey does not match with the label and description
Proposed change: Invalidate the value 3D seismic survey 
Change type: Invalidation

Motivation: The definition of the value time domain EM survey does not match with the label and description
Proposed change: Invalidate the value time domain EM survey 
Change type: Invalidation

Motivation: The definition of the value frequency domain EM Survey does not match with the label and description
Proposed change: Invalidate the value frequency domain EM Survey 
Change type: Invalidation

**Comment by hernlor** [comment]
Dear @lvdbrink , 

thank you for your request and for pointing out the mismatching labels and description for the _[SurveyTypeValue](https://inspire.ec.europa.eu/codelist/SurveyTypeValue)_ code list.

After checking the source files it looks like the problem resides on the [Data Specification for Geology](https://inspire.ec.europa.eu/Themes/128/2892) (at least the technical values not included in the [Regulation Commission Regulation (EU) No 1089/2010](https://eur-lex.europa.eu/eli/reg/2010/1089)) - see picture attached-. 
The definitions look fine, but the descriptions look like having been swapped. 
![image](https://user-images.githubusercontent.com/80747974/113702963-7da60000-96da-11eb-9b22-78a06e580224.png)

On how to manage this issue, "invalidation" is generally only used when the URI is wrong and cannot be reused. This does not look like to be the case, therefore we could go ahead with simple corrections ["Clarifications" option according to ISO191135 workflow implemented by the INSPIRE registry].

We cannot change the data specification for Geology, but you might provide the correct descriptions for each of the code list values for the review of the control body. Could that be an option to go ahead?

Kind regards, 
INSPIRE registry team

**Comment by arantzaetxebarria** [comment]
The label "requires change in TG" has been deleted because no changes to the TG are necessary, as requested in the issue https://github.com/INSPIRE-MIF/technical-guidelines/issues/6 from now on in the TG all data specifications will be replaced with a link to the code list in the INSPIRE Registry.
This way all changes are centralised in the INSPIRE registry.

**Comment by jescriu** [comment]
Dear @idevisser,
As representative of the Submitting Organisation from the NL, could you please confirm your support to this change proposal?
Thank you.

**Comment by idevisser** [comment]
Dear @jescriu,
I contacted the expert that brought this issue  to our attention. He agreed that
 "invalidation" does not look like to be the case, therefore we could go ahead with simple corrections on the descriptions.

**Comment by arantzaetxebarria** [comment]
In the sub-group meeting on 10/11/2023, the proposal was accepted, but additional support is needed to complete the missing descriptions (see in the table above the empty fields of the column "Correct description")

**Comment by fabiovinci** [comment]
The INSPIRE MIG-T approved the change proposal during the [76th MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/76th+MIG-T+meeting+2023-11-30).
In the next step, the proposal will be moved to the MIG for the final endorsement.

**Comment by jescriu** [comment]
Dear @arantzaetxebarria,
I checked your table with the proposed changes [above](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/14#issuecomment-1770214440) and all 'Correct description' fields perfectly fit with the associated coelist value.
Please doublecheck that none of the 'Current description' fields is missing. I expect 5 descriptions repeated in this column.
After that please proceed implementing the proposal througn the INSPIRE Registry admin interface.
Thank you.

**Comment by arantzaetxebarria** [comment]
Dear @lvdbrink, @idevisser 

We would like to inform you that the restructuring of the codelist [SurveyTypeValue](https://inspire.ec.europa.eu/codelist/SurveyTypeValue) descriptions have been successfully published.

Regards
