### ISSUE TITLE
codelist vs codeList

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-registry#15]
In the INSPIRE Registry both links exist:

http://inspire.ec.europa.eu/codelist (lowercase)
http://inspire.ec.europa.eu/codeList (camelCase)

even if both are indicating that the correct version is codelist (lowercase).

![image](https://user-images.githubusercontent.com/20813598/113984011-49a21a80-9853-11eb-9497-ee82e40e1846.png)

This suggest that the http://inspire.ec.europa.eu/codeList is pointing to the same page as http://inspire.ec.europa.eu/codelist.

However the users are not noticed that http://inspire.ec.europa.eu/codeList is Invalid by displaying a simmilar text to the one bellow, as this was implemented only for code lists values, and not also for code lists (parents of the code lists values):

![image](https://user-images.githubusercontent.com/20813598/113984294-98e84b00-9853-11eb-822b-f8f09992efd0.png)

This actually allows users to provide the code lists values with both codelist and codeList without receiving any error or without being noticed that codeList is not valid, while only codelist is valid. This creates some problems in parsing the codelists from the Member States datasets when using case sensitive collations or in Linux/Unix systems that are mainly used for such developments.

![image](https://user-images.githubusercontent.com/20813598/113985662-1496c780-9855-11eb-8823-75515acba84f.png)

Some discussions about this incident exist here:
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/407

**Comment by arantzaetxebarria** [comment]
The issue is solved
The URL https://inspire.ec.europa.eu/codeList access gives a 404.
Also, the example of the user only works with lowercase.
https://inspire.ec.europa.eu/codeList/MeasurementRegimeValue/continuousDataCollection
https://inspire.ec.europa.eu/codelist/MeasurementRegimeValue/continuousDataCollection
