### ISSUE TITLE
Duplication of labels in the code list "Classification of spatial data services"

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-registry#16]
**URI**: https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory

**Motivation**: The labels for some items in the code list "Classification of spatial data services" are duplicated both in English and in Italian although they concern different items. This occurs in the following cases:
- the items http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/spatialFeatureGeneralizationService and  http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/thematicFeatureGeneralizationService;
- the items http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/thematicSubsettingService, http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/temporalSubsettingService and http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/spatialSubsettingService;
- the items http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/spatialSamplingService and http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/temporalSamplingService.

**Proposed changes**:
- change label of http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/spatialFeatureGeneralizationService from "Feature generalisation service" to "Spatial feature generalisation service" in English and from "Servizio di generalizzazione di elementi" to "Servizio di generalizzazione di elementi territoriali" in Italian;
- change label of http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/thematicFeatureGeneralizationService from "Feature generalisation service" to "Thematic feature generalisation service" in English and from "Servizio di generalizzazione di elementi" to "Servizio di generalizzazione di elementi tematici" in Italian;
- change label of http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/thematicSubsettingService from "Subsetting service" to "Thematic subsetting service" in English and from "Servizio di definizione dei sottoinsiemi" to "Servizio di definizione dei sottoinsiemi tematici" in Italian;
- change label of http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/temporalSubsettingService from "Subsetting service" to "Temporal subsetting service" in English and from "Servizio di definizione dei sottoinsiemi" to "Servizio di definizione dei sottoinsiemi temporali" in Italian;
- change label of http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/spatialSubsettingService from "Subsetting service" to "Spatial subsetting service" in English and from "Servizio di definizione dei sottoinsiemi" to "Servizio di definizione dei sottoinsiemi territoriali" in Italian;
- change label of http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/spatialSamplingService from "Sampling service" to "Spatial sampling service" in English and from "Servizio di campionamento" to "Servizio di campionamento territoriale" in Italian;
- change label of http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/temporalSamplingService from "Sampling service" to "Temporal sampling service" in English and from "Servizio di campionamento" to "Servizio di campionamento temporale" in Italian.

**Change type**: clarification

**Comment by hernlor** [comment]
Dear @AntoRot ,

Thank you for pointing out the duplications and for providing the correct labels both in English and Italian.

These will be corrected in the next content update. 

We will let you know when this happens.

Kind regards,

INSPIRE Registry team.

**Comment by fabiovin** [comment]
Dear all,

the labels come from the IR and are based on the geographic services taxonomy of EN ISO 19119, and unfortunately, some names are duplicated and they can be distinguished only by the "XML value" or by the "Domain code".

Example for "Feature generalisation service":
![image](https://user-images.githubusercontent.com/46569952/115376934-6d5c4d80-a1cf-11eb-9b68-16d4b8a07e19.png)

![image](https://user-images.githubusercontent.com/46569952/115376945-70efd480-a1cf-11eb-806f-8773f3e2b335.png)

I think that to maintain consistency with the other values all the labels should be updated and not only the duplicated ones.

A solution could be to add the "Domain code" to all the existing label values or to use the "XML value", for instance:

- "415 - Feature generalisation service" and "503 - Feature generalisation service"
or
- "spatialFeatureGeneralizationService" and "thematicFeatureGeneralizationService"

**Comment by AntoRot** [comment]
Dear @fabiovin,

Thank you for pointing out that the duplications in the labels come from the IR (and from ISO 19119 taxonomy). I didn't remember that.

Going deeper, I saw that the taxonomy is organised in categories and subcategories, as also pointed out in the part D.4 in IR. For this reason we can have the same label for several items as the differentiation can be made at the level of category (and not subcategory).

I think that the best solution could be the first one you proposed, i.e. adding the domain code in the label value as also reported in the IR (i.e. 415 Feature generalisation service). 

Kind regards,
Antonio

**Comment by hernlor** [comment]
Dear @AntoRot , thank you for the patience. 

We have discussed internally the option kindly shared by @fabiovin. We understand that the proposed approach would give more clarity while in line with the IR.

However, the change would imply a massive change in the whole code list (including the translated versions), impacting many metadata files.

To assess better whether to approve or not the change, could you please illustrate better where the current code list creates an issue?

Kind regards on behalf of the INSPIRE registry control body

**Comment by arantzaetxebarria** [comment]
The change proposal has been published in INSPIRE Registry https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory
