### ISSUE TITLE
Add some new items in the Protocol Value register

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-registry#17]
**URI**: http://inspire.ec.europa.eu/metadata-codelist/ProtocolValue

**Motivation**:  We propose to add some items in the Protocol Value register because we need some missing codes to represent two types of resources, i.e.:
- a web page with further instructions for accessing the data set described through metadata;
- direct access for downloading the data set described through metadata.

**Proposed change**: new proposed items:
- WWW:LINK
   Register: http://inspire.ec.europa.eu/metadata-codelist/ProtocolValue Label: Web Address (URL) URI: http://www.w3.org/TR/xlink/ External value: true

- WWW:DOWNLOAD
   Register: http://inspire.ec.europa.eu/metadata-codelist/ProtocolValue Label: File for download Definition: Link that will get resource URI: http://inspire.ec.europa.eu/metadata-codelist/ProtocolValue/www-download External value: false

**Change type**: addition

**Comment by hernlor** [comment]
Dear @AntoRot , 

Thank you for your request.

The scrutiny period begins now, and it is open to comments from Control Body during the next two weeks.

Kind regards,
 
INSPIRE Registry team.

**Comment by AntoRot** [comment]
Thank you very much, @hernlor!

Please note that this addition will also imply a revision of the definition of the register.

Kind regards,
Antonio

**Comment by hernlor** [comment]
Dear @AntoRot thank you for the patience. 

We have discussed internally your proposal.

The addition of new values would imply a change in the definition and reasoning behind the code list as you rightly pointed out. 

Because of the latter, the control body prefers not to approve the change at the moment and invites you to discuss their addition in the frame of  "Action 2.3 "Simplification of INSPIRE implementation"[1] of the INSPIRE MIWP 2021-2024[2].

Alternatively, you can create an extension of the code lists to support your use case and share it through the Registry of registers applications.

[1] https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification
[2] https://webgate.ec.europa.eu/fpfis/wikis/display/InspireMIG/INSPIRE+work+programme+2021-24 
 
Kind regards on behalf of the[ INSPIRE Registry control body](https://github.com/INSPIRE-MIF/helpdesk-registry/blob/main/control-body-list.md).

**Comment by AntoRot** [comment]
Dear @hernlor,

Thank you for the attention of the INSPIRE Registry control body to the change proposal.

Our initial intention indeed was to publish the two items in the Italian registry (included in the INSPIRE register federation) as national extensions to the Protocol Value register, but we thought to first propose this change to the INSPIRE registry as it could be of interest for other Member States.

Now we'll proceed as you suggested, by both publishing the national extensions and discussing the proposal under the new action 2.3. 

Anyway, I think that register should include all the possible reference codes to be used as protocol values and not be limited only to the scope defined under the simplification action.  

Best regards,
Antonio

**Comment by hernlor** [comment]
Thank you @AntoRot, 

feel free to reopen this issue or link to this one after discussing the options under Action 2.3 "Simplification of INSPIRE implementation" of the INSPIRE MIWP 2021-2024.

Kind regards, 

INSPIRE Registry team

**Comment by jescriu** [comment]
Dear @AntoRot,
Taking into account the final progress on the Data-service linking simplification good practice proposal, under Action 2.3.2 [Simplification of INSPIRE implementation](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification), I proceed to reopen again this issue for further consideration by the Control Body.
Jordi

**Comment by AntoRot** [comment]
In the light of the provisions laid down by the Implementing Regulation (EU) 2023/138 (High-value datasets) and specifically the arrangement about the availability of datasets as bulk download, I think that this proposal should be reconsidered.

The new proposed item WWW:DOWNLOAD indeed could be used to denote the mandatory bulk download for spatial datasets falling under the above mentioned Regulation.

**Comment by arantzaetxebarria** [comment]
In the MIWP Action 2.3.1 MIG-T Sub-group Meeting on 06/05/2024, it was agreed to bring this proposal for endorsement in the [78 MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/78th+MIG-T+meeting+2024-05-17).

**Comment by arantzaetxebarria** [comment]
The INSPIRE MIG-T approved the change proposal during the [78 MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/78th+MIG-T+meeting+2024-05-17)

**Comment by arantzaetxebarria** [comment]
We want to inform you that the proposal has been successfully published.

https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue
https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue/www-download

Regards
