### ISSUE TITLE
Nomination NL

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-registry#18]
- Country: NL
- Organisation: Geonovum
- Contact name: Ine de Visser
- Contact e-mail: i.devisser@geonovum.nl

Replacing  the current person

**Comment by hernlor** [comment]
Dear @idevisser , 

thank you for your nomination. 
The [list](https://github.com/INSPIRE-MIF/helpdesk-registry/blob/main/submitting-organisations-list.md) of submitting organisations representatives is now updated.

Kind regards, 
INSPIRE registry team
