### ISSUE TITLE
INSPIRE Registry unstable and has significant latency

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-registry#2]
Hi everyone,

it seems that INSPIRE Registry is quite unstable and that connection to the registry breaks very often. 

Applications like INSPIRE validator are using the registry for many use cases (validation of INSPIRE Themes, Spatial Scope, Priority Data Sets, ...). I assume that other applications are also accessing some ressources from the registry in order to check the compliance. Some applications solved this problem by caching the ressources in order to avoid connection break.

More information:

https://github.com/inspire-eu-validation/community/issues/454

Second problem regarding INSPIRE registry was also reported in INSPIRE Validator Community due to external dependency to the registry. It seems that registry also respond very slow and it has significant latency.

More information:

https://github.com/inspire-eu-validation/community/issues/399

This problems are already confirmed in INSPIRE Forum:

https://inspire.ec.europa.eu/forum/discussion/view/269974/inspire-registry-unstable-and-has-significant-latency

Kind regards,
Dejan

**Comment by DeordD** [comment]
When can we expect that update on the INSPIRE Registry production instance?

Regarding your remark concerning good practice to create a cache of such a service -

after closer look on INSPIRE Registry use cases, especially https://ies-svn.jrc.ec.europa.eu/projects/inspire-registry/wiki/Use_cases#Use-case-V-Validation-of-data the intention ist to connect to the registry on the fly without needing to create local copy of the registry or create a cache of such service.

**Comment by df-git** [comment]
Dear @DeordD,
We are sorry for the delay in coming back to you.
Thank you for pointing out this technical issues. Our aim is to enhance them in the next release of  INSPIRE Registry service.
We are currently working in upgrading the version of the software that powers the INSPIRE registry ([Re3gistry 2.0](https://github.com/ec-jrc/re3gistry)). We expect to have it deployed in Spring time. 
Best regards,
Daniele on behalf of the INSPIRE Support Team

**Comment by DeordD** [comment]
Hi @df-git,

did you already deployed the new version of the registry? 

Are you also aware of the cross-platform problem which has been communicated [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/545)? Can you confirm the problem?

Thanks in advance!

**Comment by df-git** [comment]
Hi @DeordD,
Thank you for your feedback.
The new version of the INSPIRE Registry has not yet been released.
It should be released during the summer.
