### ISSUE TITLE
inconsistencies - names of the registers

### ISSUE THREAD

**Issue by bfrichet3** [INSPIRE-MIF/helpdesk-registry#21]
Dear

I noticed that the name of the different registers are quite inconsistent. As you may see in the registryEN.png file I uploaded (containing the xml file describing the registries), the specific topic of some registers are written in the plural form ("INSPIRE media-**types** register"), when some are not (INSPIRE theme register): this is quite inconsistent. 

I face the same difficulty when I read the French or the Dutch version of that XML or when I read the associated HTML pages. Furthermore, some of the french register names are written with the plural form ("Registre de **listes** de codes") and the english versions are written with the singular form ("INSPIRE code list". This is even more incosistent and unexpected.

Last time I check, there were many INSPIRE themes, as there were were many INSPIRE applciation schemas, and so on. Could you fix all these inconsistencies and add plural where this is needed?

Regards
![registryFR](https://user-images.githubusercontent.com/80756452/136785683-07bb83fa-caca-4f96-88d2-ebf90d8b16aa.png)
![registryEN](https://user-images.githubusercontent.com/80756452/136785692-45e0a0f3-0932-4997-b5b2-888138205d56.png)

**Comment by arantzaetxebarria** [comment]
In the MIWP Action 2.3.1 MIG-T Sub-group Meeting on 06/05/2024, it was agreed NOT to correct these minor inconsistencies. So the issue is closed
