### ISSUE TITLE
Add localisation for Italian and German in the metadata code list 'Conditions Applying To Access and Use' 

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-registry#23]
**URI**: https://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse

**Motivation**: We need to have the locatisation for Italian and German in order to express the access and use conditions in the metadata languages used in Italy (German is used in some regions).

 **Proposed change**: 
- add the Italian translation of the code list label, i.e. "Condizioni applicabili all'accesso e all'uso"
- add the German translation of the code list label i.e. "Bedingungen für den Zugang und die Nutzung"
- add the Italian translation of the label of the item https://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/conditionsUnknown, i.e. "condizioni per l'accesso e l'uso sconosciute"
- add the German translation of the label of the item https://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/conditionsUnknown, i.e. "Zugangs- und Nutzungsbedingungen unbekannt"
- add the Italian translation of the label of the item https://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply, i.e. "nessuna condizione per l'accesso e l'uso"
- add the German translation of the label of the item https://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply, i.e. "keine Auflagen für Zugang"

**Change type**: addition

Thank you in advance.

Regards,
Antonio

**Comment by alitka** [comment]
Minor adjustments for the German entries:
1. for the codelist "Limitations on public access"
- add the German translation of the label of the item http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations to ``Es gelten keine 
Zugriffsbeschränkungen``
- add the German translation of the label of the item http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1a to ``Öffentlicher Zugriff beschränkt entsprechend Artikel 13(1)(a) der INSPIRE-Richtlinie: a) aufgrund nachteiliger Auswirkungen auf die Vertraulichkeit der Verfahren von Behörden``
- add the German translation of the label of the item http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1b to ``Öffentlicher Zugriff beschränkt entsprechend Artikel 13(1)(b) der INSPIRE-Richtlinie: b) aufgrund nachteiliger Auswirkungen auf internationale Beziehungen, die öffentliche Sicherheit oder die Landesverteidigung``
- add the German translation of the label of the item http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1c to ``Öffentlicher Zugriff beschränkt entsprechend Artikel 13(1)(c) der INSPIRE-Richtlinie: c) aufgrund nachteiliger Auswirkungen auf laufende Gerichtsverfahren``
- add the German translation of the label of the item http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1d to ``Öffentlicher Zugriff beschränkt entsprechend Artikel 13(1)(d) der INSPIRE-Richtlinie: d) aufgrund nachteiliger Auswirkungen auf die Vertraulichkeit von Geschäfts- oder Betriebsinformationen``
- add the German translation of the label of the item http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1e to ``Öffentlicher Zugriff beschränkt entsprechend Artikel 13(1)(e) der INSPIRE-Richtlinie: e) aufgrund nachteiliger Auswirkungen auf die Rechte des geistigen Eigentums``
- add the German translation of the label of the item http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1f to ``Öffentlicher Zugriff beschränkt entsprechend Artikel 13(1)(f) der INSPIRE-Richtlinie: f) aufgrund nachteiliger Auswirkungen auf die Vertraulichkeit personenbezogener Daten``
- add the German translation of the label of the item http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1g to ``Öffentlicher Zugriff beschränkt entsprechend Artikel 13(1)(g) der INSPIRE-Richtlinie: g) aufgrund nachteiliger Auswirkungen auf den Schutz einer Person``
- add the German translation of the label of the item http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1h to ``Öffentlicher Zugriff beschränkt entsprechend Artikel 13(1)(h) der INSPIRE-Richtlinie: h) aufgrund nachteiliger Auswirkungen auf den Schutz von Umweltbereichen``

2. for the codelist "Conditions Applying To Access and Use"
- add the German translation of the label of the item http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/conditionsUnknown to ``Bedingungen unbekannt``
- add the German translation of the label of the item http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply to ``Es gelten keine 
Bedingungen``

Thanks in advance and best regards.

**Comment by alitka** [comment]
Just a little reminder: it would be great, if you could add, inter alia, the localization for German in the metadata code list ``Limitations on public access`` and ``Conditions Applying To Access and Use`` as soon as possible.
Thanks and best regards!

**Comment by arantzaetxebarria** [comment]
Dear @AntoRot 

We would like to inform you that despite having carried out the corresponding actions for this change proposal, these have not been successfully published.
We are trying to investigate the source of the problem and try to solve it.
We apologise for the inconvenience.

**Comment by arantzaetxebarria** [comment]
Dear @AntoRot 

It has been verified that the re-caching problems have been solved and the publications are effective.

The issue can then be closed
