### ISSUE TITLE
Soil theme WRBQualifierValue code list has no values

### ISSUE THREAD

**Issue by ldesousa** [INSPIRE-MIF/helpdesk-registry#24]
The **WRBQualifierValue** code list defined in the [Soil themes guidelines document](https://inspire.ec.europa.eu/id/document/tg/so) seems to be empty. The root of this code list is reacheable:
https://inspire.ec.europa.eu/codelist/WRBQualifierValue

But all the actual values I have tried so far return a 404 error. For instance:

https://inspire.ec.europa.eu/codelist/WRBQualifierValue/arenic

https://inspire.ec.europa.eu/codelist/WRBQualifierValue/areninovic

https://inspire.ec.europa.eu/codelist/WRBQualifierValue/escalic

**Comment by pvgenuchten** [comment]
Codelist is available at https://www.fao.org/fileadmin/templates/nr/images/resources/pdf_documents/wrb2007_red.pdf annex 2

**Comment by arantzaetxebarria** [comment]
Dear @ldesousa

These values are external codelist,  and if you click the [document field link](https://inspire.ec.europa.eu/document/WRBQu), you can access the document commented by @pvgenuchten https://www.fao.org/fileadmin/templates/nr/images/resources/pdf_documents/wrb2007_red.pdf where the values are present.

Regards,

Arantza
