### ISSUE TITLE
Planned Land Use Mapping table

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-registry#26]
Dear all,

does anyone know why it is not possible to open a mapping table for Planned Land Use from https://inspire.ec.europa.eu/Themes/129/2892?

**Comment by heidivanparys** [comment]
You should download the xml file to your file system. If you then start Excel, and open the file from there, it should work.

![image](https://user-images.githubusercontent.com/11427611/144265310-eb75066a-a0b9-4849-bc94-13435c92653e.png)

![image](https://user-images.githubusercontent.com/11427611/144265447-e25b01d9-bc1e-4913-87f7-134ec8207c53.png)

It is an old type of [Microsoft Office format](https://en.wikipedia.org/wiki/Microsoft_Office_XML_formats):
![image](https://user-images.githubusercontent.com/11427611/144265166-f8e11903-894d-455f-aa59-4139192ac811.png)

**Comment by Ana-SGA** [comment]
Dear @heidivanparys ,

thanks, I always download xml and open it from excel, but I was confused by the error (attached). But you are right, regardless of the error, after downloading it opens from excel without problems. Thanks again!

![PLU](https://user-images.githubusercontent.com/77394573/144368772-b2896d12-35e4-49e7-8e72-fb27d022fbaf.PNG)

**Comment by emanuelaepure10** [comment]
Thank you @Ana-SGA  for reporting it 
and thank you @heidivanparys for the solution
