### ISSUE TITLE
Email to access administration area of RoR not deliverable

### ISSUE THREAD

**Issue by fhb1990** [INSPIRE-MIF/helpdesk-registry#3]
I am trying to get access to the administration area of the RoR, in order to link our national codelist register.
According to [this page](https://inspire-regadmin.jrc.ec.europa.eu/ror/help.jsp), I need to send a request to inspire-registry-dev@jrc.ec.europa.eu. However, this address doesn't seem to exist. Is there another address I can send the request to?

Kind regards

**Comment by df-git** [comment]
Dear @fhb1990,
Thank you for your feedback. The e-mail has been updated. 
Please use jrc-inspire-support@ec.europa.eu

Best regards,
Daniele on behalf of the INSPIRE Support Team
