### ISSUE TITLE
Front end update of changes @ backend

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-registry#31]
Dear Re3gistry team,

I have update updated label for the original register with name "[test1](https://er.hany.sk/test1)"
![obrázok](https://user-images.githubusercontent.com/6195936/156801027-6c55c21f-356f-4ebd-9b03-bd89b65637c6.png)

into the value "Codelists"
![obrázok](https://user-images.githubusercontent.com/6195936/156801181-a7321da4-bdb5-4c93-bd66-ddb159488b3a.png)

Also updatge was aproved changes on all levels, I still don't see change on the front end.

Any idea, what might be the problem?

Thanks in advance, 

Martin

**Comment by emanuelaepure10** [comment]
Hi @MartinTuchyna 

Do you have the latest version?
With the latest version we have done a nice improvement that before was not there, that on publishing an action as well the cache is updated so the page that you want to see.

Please let us know
Best regards
