### ISSUE TITLE
Add a new item in the ProtocolValue register for OGC API-Features

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-registry#32]
**URI**: http://inspire.ec.europa.eu/metadata-codelist/ProtocolValue

**Motivation**:  [OGC API-Features as an INSPIRE download service](https://inspire.ec.europa.eu/good-practice/ogc-api-%E2%80%93-features-inspire-download-service) was endorsed as Good Practice. We propose to add an item in the Protocol Value register related to that OGC API-Features standard.

**Proposed change**: new proposed item:
- OGC API-Features
   Register: http://inspire.ec.europa.eu/metadata-codelist/ProtocolValue 
   Label: OGC API-Features 
   URI: [http://www.opengis.net/def/interface/ogcapi-features](https://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/interface/ogcapi-features) 
   External value: true

**Change type**: addition

**Comment by arantzaetxebarria** [comment]
Since the URI mentioned in the change proposal no longer works, @AntoRot  has provided us with this new value

URI: http://www.opengis.net/def/docs/17-069r3

**Comment by arantzaetxebarria** [comment]
The change proposal has been published in INSPIRE Registry https://inspire.ec.europa.eu/re3gistry/content?itemUuid=dab5f8ecae0aade3b9561e4a6b78a95a&languageUuid=en

**Comment by PB-GNM** [comment]
URI: http://www.opengis.net/def/docs/17-069r3 does not work either.
maybe:
https://docs.ogc.org/is/17-069r4/17-069r4.html
