### ISSUE TITLE
Error in Registry access: "The format or language specified in the request is not available"

### ISSUE THREAD

**Issue by jetgeo** [INSPIRE-MIF/helpdesk-registry#39]
I am now longer able to access the INSPIRE Registry (https://inspire.ec.europa.eu/registry) from Norway. I get the same error independent of the browser, PC or phone I am using:

```
Error message
The format or language specified in the request is not available. Please specify a supported format/language. For additional info, you can contact [jrc-inspire-support@ec.europa.eu](mailto:jrc-inspire-support@ec.europa.eu)
```

I have never experienced this error before.

**Comment by oscar9** [comment]
Dear jetgeo,

Thank you for reporting this bug. We will analyze it and we will give you an answer as soon as possible. If the error is related to the re3gistry software it will be moved to the corresponding helpdesk.

Best regards

**Comment by jetgeo** [comment]
Any news on this issue? Have you been able to analyze it?  FYI, I tried changing language for my system to English, but that did not help. Also, I have tried accessing from Paris, France today, but still get the same error.

**Comment by oscar9** [comment]
Hi @jetgeo ,

We have replicated the error by setting the browser to Norwegian by default. This error is related to the re3gistry application as it is taking Norwegian and this language is not available. We are going to create a ticket in the [helpdesk ](https://github.com/ec-jrc/re3gistry/issues)of the related re3gistry to fix it.

In the meantime, one solution is to change the language when entering as indicated in the images on the INSPIRE Registry website. 

![image](https://user-images.githubusercontent.com/4819782/201672790-e58a563c-3bf5-451b-ba3d-24e76c00067e.png)

Another alternative would be to change the language of the browser but this would affect all navigation.
![image](https://user-images.githubusercontent.com/4819782/201672876-e495c33d-31fa-4c56-9d09-e3e28a18621c.png)

Thanks for reporting this issue, we will comment again in this issue with a link to the new issue in the Re3gistry helpdesk.

Best regards,
Óscar

**Comment by jetgeo** [comment]
Thanks, @oscar9 . I can confirm that I am able to access the Registry by setting the language as described. May I suggest that for all users where the language is not supported, English is used by default? INSPIRE is being referred to as an example for many parts of the world (for example by UN-GGIM and Geospatial World), many with non-EU languages.

**Comment by arantzaetxebarria** [comment]
Has been created this [issue ](https://github.com/ec-jrc/re3gistry/issues/238) in the Re3gistry software to fix the problem.
