### ISSUE TITLE
No contents in archive for old helpdesk

### ISSUE THREAD

**Issue by laers** [INSPIRE-MIF/helpdesk-registry#4]
I am trying to find an old issue in the old help desk. According to INSPIRE Knowledge Base the contents is available at
https://wayback.archive-it.org/12090/20210104094606/https://ies-svn.jrc.ec.europa.eu/projects/geoportal/issues

But there seems to be a problem - only issues at page 1 is available. Page 2 and forward does not excist.

//Lars

**Comment by df-git** [comment]
Dear @laers,
Thank you for your message.
You can find the full list of issues here: https://wayback.archive-it.org/12090/20201221124650/https://ies-svn.jrc.ec.europa.eu/issues
In this page, the pagination is working.
