### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by radochudy** [INSPIRE-MIF/helpdesk-registry#41]
After new realeas of INSPIRE registry we are facing CORS errors in our applications https://rpifrontend.synchronix.sk:8443/metadata . Also our instance of INSPIRE validator during validation of metadata, data which use reference to INSPIRE registry is reporting error
e.g. System error in the Executable Test Suite. Please contact a system administrator. Error information:Access to code list http://inspire.ec.europa.eu/theme failed or timed out. 

![image](https://user-images.githubusercontent.com/6662421/198741118-fd234048-43ab-483e-a58a-e09ae8882215.png)

**Comment by klimeto** [comment]
Of very high interest also to us

**Comment by oscar9** [comment]
Dear radochudy & klimeta,

Thanks for contacting us. This report looks like two different issues.
CORS error
-	if this error happens randomly, it could imply a work saturation in the INSPIRE Registry server. Related to #40. 
-	If this error happens constantly, it could imply a lack of a specific header in the Re3gistry response. Please could you give us more feedback about this issue? When is happening? A specific URL? We are not able to reproduce your attached image. Depending on your answer we would move this error to the Re3gistry software helpdesk.
Validator error
-	As said, this could be related to issue #40 and It could imply an overload of work in the INSPIRE Registry. Please let us know if this error appears constantly and for what links are failing (we see that in this case is accessing to the theme code list)

Best regards,
Óscar

**Comment by radochudy** [comment]
Dear oscar,

problem is permanent. We are unable to load data from registry due to CORS error.... 
https://rpifrontend.synchronix.sk:8443/en/metadata

![image](https://user-images.githubusercontent.com/6662421/200581665-498d97a1-873e-4e5b-8913-f7d81fbc0fbc.png)

**Comment by oscar9** [comment]
Dear everyone,

We have analyzed the error and found a solution for it. We are in the process of testing the solution and if everything works correctly, it will be updated on the production server. Thanks for waiting.

Best regards,
Óscar

**Comment by klimeto** [comment]
Great news @oscar9 please ping us when deployed in the production so we revert our config back to inspire registry URL.

**Comment by arantzaetxebarria** [comment]
Dear @radochudy, @klimeto 

As the implemented solution has been made from the Re3gistry software, and to add in the next release, a new issue has been opened in its repository and this issue will be closed. 

So from now on, you can track the resolution through this [issue ](https://github.com/ec-jrc/re3gistry/issues/240). 

Regards
