### ISSUE TITLE
Random 502 errors while retrieving SpatialDataServiceCategory inspire registry

### ISSUE THREAD

**Issue by mwjsanders** [INSPIRE-MIF/helpdesk-registry#42]
We are running the INSPIRE Reference Validator v2022.3 locally in a docker container (ghcr.io/inspire-mif/helpdesk-validator/inspire-validator:2022.3) for validating inspire services and its metadata.

During validation of the ATOM metadata, the inspire validator reports in some cases 502 http response statusses during retrieval of the INSPIRE registry http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/SpatialDataServiceCategory.en.xml
The 502 seems to happen randomly and every time on different service metadata. Off 63 ATOM service metadata validations, 11 validations report the 502 error while the other's don't (so about 1/6 fails). 

The reported error in the inspire validator:
```
System error in the Executable Test Suite. Please contact a system administrator. Error information:[err:FODC0002] Server returned HTTP response code: 502 for URL: http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/SpatialDataServiceCategory.en.xml
Information:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</strong></p></p>
<hr>
<address>Apache/2.4.10 (Debian) Server at inspire.ec.europa.eu Port 80</address>
</body></html>
 
 (563/40)

```
![inspire-val_snapshot](https://user-images.githubusercontent.com/22592588/199216550-51d3f4a8-554a-456c-8db1-3e1d42bda838.PNG)

I was not able to reproduce this error while using the online reference validator https://inspire.ec.europa.eu/validator/home/index.html

**Comment by oscar9** [comment]
Dear @mwjsanders ,

Thanks for reporting the issue. These errors usually occur due to work saturation. In any case, we will take it into account. Please give us feedback if they continue to occur consistently or it is happening for a specific service.

Best regards

**Comment by mwjsanders** [comment]
Dear @oscar9 

Thanks for looking into this issues.

These errors happened since 25th November and do still occur on some ATOM service metadata tests, although most of the ATOM service metadata tests can successfully resolve http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/SpatialDataServiceCategory.en.xml. 
Every time the errors happen on different service metadata records, so it does not seem te be related to the metadata itself.

We run about 200 service tests and 200 metadata test using al localy running reference validator (ghcr.io/inspire-mif/helpdesk-validator/inspire-validator:2022.3). The tests are performed sequentially which takes about 4 hours to validate all service and metadata

**Comment by fabianospinelli** [comment]
Dear @mwjsanders ,
Thank you for reporting this issue. I kindly ask you to repeat the validation of ATOM metadata as we have made some improvements on the server (others will follow) and we would like to understand if this problem may have been resolved.
Thanks for your help and I look forward to your feedback.

**Comment by mwjsanders** [comment]
Dear @fabianospinelli,

Unfortunately the 502's on http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/SpatialDataServiceCategory.en.xml request do still happen randomly. We don't have any issues with any other codelists though.

**Comment by mwjsanders** [comment]
@arantzaetxebarria 
 I can confirm that the random 502 responses don't happen any more on inspire codelist value retrieval during validation of inspire services and their metadata.

The only issue with inspire codelist retrieval we see is during dataset metadata validation in some cases (most of the time the retrieval of the codelist is successful):
```
System error in the Executable Test Suite. Please contact a system administrator. Error information:[err:FOER0000] Access to code list http://inspire.ec.europa.eu/metadata-codelist/SpatialScope failed or timed out. 
```

**Comment by arantzaetxebarria** [comment]
Dear @mwjsanders 

Due to the 502 error has been solved, the issue will be closed.
Do not hesitate to open a new one in case of new problems.

Regards
