### ISSUE TITLE
Codelist iso19135 format missing the <status> element for each entry

### ISSUE THREAD

**Issue by OTWillems** [INSPIRE-MIF/helpdesk-registry#45]
An FME application I developed for Dutch local government checks in a codelist if an entry is still valid. My logic can't determine if an entry is valid because the status node is missing in the ISO 19135 format.

INSPIRE Registry Codelist that has the issue:
https://inspire.ec.europa.eu/codelist/EnvironmentalDomain

INSPIRE codelist as ISO 19135
https://inspire.ec.europa.eu/codelist/EnvironmentalDomain/EnvironmentalDomain.en.iso19135xml

The ISO 19135 XSD it's referring to:
https://standards.iso.org/iso/19135/-2/reg/1.0/registration.xsd#:~:text=%3CcomplexType%20name%3D%22RE_RegisterItem_Type,%3C/complexType%3E

The part of the XSD stating that status is mandatory:

```
<complexType` name="RE_RegisterItem_Type">
<complexContent>
<extension base="pre:Abstract_RegisterItem_Type">
<sequence>
<element maxOccurs="unbounded" minOccurs="0" name="predecessor" type="reg:RE_RegisterItem_PropertyType"/>
<element name="itemIdentifier" type="gco:Integer_PropertyType"/>
<element name="name" type="gco:CharacterString_PropertyType"/>
<element name="status" type="reg:RE_ItemStatus_PropertyType"/>              <<<<=========
<element minOccurs="0" name="dateAccepted" type="gco:Date_PropertyType"/>
<element minOccurs="0" name="dateAmended" type="gco:Date_PropertyType"/>
...
</sequence>
</extension>
</complexContent>
</complexType>
```

**Comment by arantzaetxebarria** [comment]
Dear @OTWillems 

Thanks for reporting the issue, an analysis is being done. We will keep you informed about our discoveries, and we will try to provide some information as soon as possible.

Regards

Arantza

**Comment by arantzaetxebarria** [comment]
Dear @OTWillems 

after analysis of this issue, it has been decided that this issue is related to the Re3gistry software, and the better place to be solved in the most efficient way would be in its corresponding helpdesk. A https://github.com/ec-jrc/re3gistry/issues/250 has been opened in its repository and this issue will be closed.

Thanks for your help and we encourage you to follow the new issue in case new information is needed.

Regards
