### ISSUE TITLE
SeaBedCoverValue code list not available

### ISSUE THREAD

**Issue by aavelepland** [INSPIRE-MIF/helpdesk-registry#54]
Registri and code lists give error message
https://inspire.ec.europa.eu/registry/
https://inspire.ec.europa.eu/codelist/SeaBedCoverValue/ [sand etc.]

![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/5802537/f859bd5e-ae30-42c8-a0e5-e5581f4b3396)

**Comment by arantzaetxebarria** [comment]
Dear @aavelepland 

Thank you for opening the issue and informing us of the problem. Could you confirm that the URL is working now?
https://inspire.ec.europa.eu/codelist/SeaBedCoverValue/sand

![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/64014694/249ba853-2c32-4c07-b924-7995303de423)
