### ISSUE TITLE
Unavailability of the INSPIRE Registry

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-registry#58]
Dear INSPIRE Team,

[INSPIRE registry](https://inspire.ec.europa.eu/registry/) is not awailable at this moment. 
![obrázok](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/6195936/c8641ad9-f6c8-436e-b0bb-fd7291b96583)
Could you please inform us, when it is foreseen to be available, as it has consequences also on some filters, we use on national [Spatial data registry](https://rpi.gov.sk/en/statistics/inspire-themes).
![obrázok](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/6195936/ac58b82c-755b-4407-95dd-c8cab2905c8c)

Thanks in advance, 

best regards, 

Martin

**Comment by jescriu** [comment]
Dear @MartinTuchyna,
Thank you for warning us about this issue.
We will analyse the problem and post you when solved.

**Comment by jescriu** [comment]
Dear @MartinTuchyna, @sMorrone,
The problem is now solved and the INSPIRE Registry is working again.
Excuses for the inconveniences.

**Comment by MartinTuchyna** [comment]
Thank you!
