### ISSUE TITLE
INSPIRE schema cannot be found via GUI of INSPIRE Registry

### ISSUE THREAD

**Issue by Anja-AjLo** [INSPIRE-MIF/helpdesk-registry#6]
If I start the INSPIRE registry, a link to the schema-repository is missing. INSPIRE-Registry (https://inspire.ec.europa.eu/registry) shows links to:
   INSPIRE application schema register	
   INSPIRE code list register	
   INSPIRE enumeration register	
   INSPIRE feature concept dictionary	
   INSPIRE glossary	
   INSPIRE layer register	
   INSPIRE media-types register	
   INSPIRE metadata code list register	
   INSPIRE reference document register	
   INSPIRE theme Register

Neither "theme Register" nor "application Schema Register" go to things I need. Actually I do not see anything I could do with these, but maybe I just do not know, yet. - I would like to refer the schema itself: 

https://inspire.ec.europa.eu/schemas/
https://inspire.ec.europa.eu/schemas/plu/
https://inspire.ec.europa.eu/schemas/plu/4.0/

In my opinion the INSPIRE registry has to link to the schema-respository (https://inspire.ec.europa.eu/schemas/). Everybody could find it easyly, if it was linked. And it was also clear to everybody all URLs of the schema-repository will be kept persitent in the centuries to come.

**Comment by arantzaetxebarria** [comment]
Dear @Anja-AjLo, @jane-heller-bkg 

In order to present this change proposal for approval in the next sub-group meeting, we would like to inform you about the details that will be carried out.

A new field called "**Reference**" will be added to include the link to the schema repository.
![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/64014694/326d03ce-3c33-4bfd-a663-d54c01bbea60)

Regarding the pages of the specific application schemas, e.g. https://inspire.ec.europa.eu/applicationschema/au, the generic link will be added: 
Reference   https://inspire.ec.europa.eu/schemas/au/

**Comment by heidivanparys** [comment]
The INSPIRE application schema register contains the application schemas, independent of the level of abstraction (conceptual models vs implementation models) and independent of the implementation technology. So I'm not sure that it would be correct to only add a link to the XML schemas.

I would like to suggest the following:

For the overview page:
![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/11427611/5bb45837-8635-44b2-9295-80e81e7770e8)

For the application schema pages:
![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/11427611/fbb6d712-02b7-4f8c-b7af-8b412d16911b)


Note: the GUID used could be either the GUID of the UML package in the UML model or the GUID of the overview diagram of the application schema. The latter is probably a bit more user-friendly.

The links work both with and without the curly braces, see e.g. https://inspire-mif.github.io/uml-models/approved/html/index.htm?guid={85BF8670-5D59-4f6c-A1B4-F95DC0AF6876} vs https://inspire-mif.github.io/uml-models/approved/html/index.htm?guid=85BF8670-5D59-4f6c-A1B4-F95DC0AF6876.

![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/11427611/4f5d4fb8-ecbc-49a2-baa3-2ea74e0c1ee6)

![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/11427611/a9b3614b-407e-4b29-83a7-157238e08934)

**Comment by GDIAnja** [comment]
The link with the curly braces does not work when opening a new tab of the browser. I receive an error 404 (??). But I like the idea of also linking the UML model for the human using the registy.

**Comment by arantzaetxebarria** [comment]
In the sub-group meeting on 10/11/2023, the proposal was accepted. 
Two new fields will be added with a link to the corresponding XML schemas and UML schema.

**Comment by heidivanparys** [comment]
> The link with the curly braces does not work when opening a new tab of the browser. I receive an error 404 (??). But I like the idea of also linking the UML model for the human using the registy.

GitHub encoded part of the URL I put in my earlier comment, so it became ```https://inspire-mif.github.io/uml-models/approved/html/index.htm?guid=%7B85BF8670-5D59-4f6c-A1B4-F95DC0AF6876%7D``` instead of ```https://inspire-mif.github.io/uml-models/approved/html/index.htm?guid={85BF8670-5D59-4f6c-A1B4-F95DC0AF6876}```, and that indeed doesn't work. So using the GUIDs without the curly braces would be the best to avoid any of this kind of issues.

**Comment by fabiovinci** [comment]
The INSPIRE MIG-T approved the change proposal during the [76th MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/76th+MIG-T+meeting+2023-11-30).
In the next step, the proposal will be moved to the MIG for the final endorsement.

**Comment by arantzaetxebarria** [comment]
We would like to inform you that the proposal has been successfully published.

Regards

**Comment by Anja-AjLo** [comment]
Thank you so much!!! From 3rd of February 2021 to 2nd of April 2024. Amazing :-)

@jane-heller-bkg Do you think we can use this for the national data models in GDI-DE Registry? We should discuss the item when we meet at the end of April.

**Comment by jane-heller-bkg** [comment]
> Thank you so much!!! From 3rd of February 2021 to 2nd of April 2024. Amazing :-)
> 
> @jane-heller-bkg Do you think we can use this for the national data models in GDI-DE Registry? We should discuss the item when we meet at the end of April.

Sure. Will forward that accordingly.
