### ISSUE TITLE
please remove the german members from the control body list

### ISSUE THREAD

**Issue by hogredan** [INSPIRE-MIF/helpdesk-registry#61]
Could you please remove Andreas von Doemming and Sebastian Kauk from the [control body list](https://github.com/INSPIRE-MIF/helpdesk-registry/blob/main/control-body-list.md) as they are no longer active in this area.

After the update of the [terms-of-references](https://github.com/INSPIRE-MIF/helpdesk-registry/blob/main/registry-control-body-and-submitting-organisations.md), it should be considered in principle to remove the list, since the control body activities have been transferred to the MIG.

**Comment by jescriu** [comment]
Dear @arantzaetxebarria,
Could you please remove this file ([control body list](https://github.com/INSPIRE-MIF/helpdesk-registry/blob/main/control-body-list.md)) and update / remove any references in the repository linking to it?

**Comment by arantzaetxebarria** [comment]
Dear @jescriu, @hogredan 

The page [control body list](https://github.com/INSPIRE-MIF/helpdesk-registry/blob/main/control-body-list.md) and their references have been removed from the repository and the documentation.

Best regards
