### ISSUE TITLE
Unavailability of the INSPIRE Registry

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-registry#65]
Dear INSPIRE Team,

[INSPIRE registry](https://inspire.ec.europa.eu/registry/) is not awailable from last night.
Could you please check it?
Thanks in advance, 
best regards, 
Martin
![obrázok](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/6195936/dc753646-c0ca-4830-b3a6-bab1b8a37fbd)

**Comment by jescriu** [comment]
Dear @MartinTuchyna,
Thank you for spotting this issue.
We will check the status of the server early next Monday.

**Comment by jescriu** [comment]
Dear @MartinTuchyna,
The issue is now solved. The server crashed because an ongoing re-caching process.
Our ICT team made some re-configuration to try to prevent this from happening again.
