### ISSUE TITLE
Old version of code list of country codes has wrong links

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/helpdesk-registry#72]
When going to https://inspire.ec.europa.eu/codelist/CountryCode:1, the previous version of the code list of country codes, some of the links shown are wrong.

![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/11427611/8f8f5733-e76e-4be4-a3af-f38a4aab2636)

My guess is that they are correct in the underlying database, but that something goes wrong on the conversion to HTML and to the formats available from the registry.

In version 2, the current version, the links are correct:

![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/11427611/1ff0ea1f-b6be-4a3d-90d5-8b1af5e6d01b)

**Comment by arantzaetxebarria** [comment]
Dear @heidivanparys 

Thank you for reporting this problem to our attention, over the next few days we will analyse the issue and come back with more information.

Regards

Arantza

**Comment by PB-GNM** [comment]
We have a simular problem with old versions and also with the current version using the latest version number (in this case 2).

So, we have errors on: 
https://test.inspireregister.nl/codelijst/geonovum-testcodelijst/testcode8:2
https://test.inspireregister.nl/codelijst/geonovum-testcodelijst/testcode8:1

And no error on:
https://test.inspireregister.nl/codelijst/geonovum-testcodelijst/testcode8 

Regards,
Pieter Bresters
Geonovum

**Comment by arantzaetxebarria** [comment]
This ticket has been moved to [Re3gistry helpdesk](https://github.com/ec-jrc/re3gistry/issues) to implement a solution. Please, from now on refer to this ticket https://github.com/ec-jrc/re3gistry/issues/371 for tracking.

Best regards
