### ISSUE TITLE
Giangprosite 

### ISSUE THREAD

**Issue by Giangpro89** [INSPIRE-MIF/helpdesk-registry#73]
Please replace these lines with a brief summary of your issue/question. Remember to specify all the required information in order to facilitate the understanding of the issue.

To help us investigate the issue, you may want to include:

- a description of the steps to reproduce your issue
- the browser and version used
- a screenshot illustrating the problem
- the URI of the reference code or the URL of the page

**Comment by arantzaetxebarria** [comment]
Dear @Giangpro89 

I am closing this ticket as it appears to have been a mistake.
Do not hesitate to contact us if you have any questions or issues.

Regards
