### ISSUE TITLE
Add to CRS Registry Official reference system of the Republic of Croatia EPSG:3765

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-registry#76]
Dear all,

we have already commented the addition of the official coordinate reference system of the Republic of Croatia to the CRS Registry - EPSG:3765. 

Since other countries are also opening issues here with requests to add their reference systems, please also include Croatian reference system EPSG:3765 to the CRS Registry (otherwise validation fails).

Thanks!

Kind regards, 
Ana

**Comment by Ana-SGA** [comment]
Dear @fabiovinci ,

thank you for info, I hope this will come to some affirmative conclusion soon. When you will have additional info, please let us know.

**Comment by arantzaetxebarria** [comment]
We would like to inform you that the proposal has been successfully published.

Regards
