### ISSUE TITLE
[CRS registry] Official reference systems of the Canary Islands

### ISSUE THREAD

**Issue by abadppa0** [INSPIRE-MIF/helpdesk-registry#77]
**Problem**: The GML files of the Canary Islands do not pass the validation requirements due to the fact that the official reference systems of the Canary Islands are not included among the CSRs listed on list of valid coordinate reference system identifiers.

**Description**:The official coordinate reference systems (CRS) of the Canary Islands are not approved. The CRS URIs of Canary are not listed in TG requirement 2.
The official CRS of the Canary Islands are:
http://www.opengis.net/def/crs/EPSG/0/4080
http://www.opengis.net/def/crs/EPSG/0/4081
http://www.opengis.net/def/crs/EPSG/0/4082
http://www.opengis.net/def/crs/EPSG/0/4083

According to the [documentation](https://github.com/inspire-eu-validation/data/blob/master/reference-systems/spatial.md) it says: Additional values will be added to the list for regions outside of continental Europe, if nominated by a Member State and available in a CRS register with a persistent http URI.

**Proposal**: Add on the "validation tool" and in the "INSPIRE Data Specifications" the official Canary Islands Coordinate Reference System Identifiers: 4080, 4081, 4082 and 4083.

Thank you.

**Comment by arantzaetxebarria** [comment]
We would like to inform you that the proposal has been successfully published.

Regards
