### ISSUE TITLE
Add EPSG:7423 as CRS for Buildings 3D

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-registry#78]
I am reposting [this old question of the INSPIRE Forum](https://wayback.archive-it.org/12090/20210119173943/https://inspire.ec.europa.eu/forum/discussion/view/268621/add-epsg7423-as-crs-for-buildings-3d) from September 2020, because it will not be addressed there any longer:

In the data specification for Buildings https://inspire.ec.europa.eu/file/1533/download?token=ouzQkBuP, EPSG:7409 is one of the default CRS. This CRS has been replaced by EPSG:7423 according to http://www.opengis.net/def/crs/EPSG/0/7409 though. Thus, I would ask to replace EPSG:7409 by EPSG:7423 in the data specification as well (or at least add EPSG:7423 additionally).

This is important because the validator interprets the list of default CRS from the data specification as exclusive and therefore throws the following exception when validating data using EPSG:7423:

"XML document 'bu-3d.gml', Building 'Building_DERPLP150000HRCB': A spatial geometry uses an unexpected coordinate reference system 'http://www.opengis.net/def/crs/EPSG/0/7423&#39;. Please refer to table 2 of the data specification for the list of expected coordinate reference systems." mentioning the following: "TG Requirement 2: The following identifiers shall be used for referring to the coordinate reference systems used in a data set: http://www.opengis.net/def/crs/EPSG/0/4936 http://www.opengis.net/def/crs/EPSG/0/4937 http://www.opengis.net/def/crs/EPSG/0/4258 http://www.opengis.net/def/crs/EPSG/0/3034 http://www.opengis.net/def/crs/EPSG/0/3035 http://www.opengis.net/def/crs/EPSG/0/3038 http://www.opengis.net/def/crs/EPSG/0/3039 http://www.opengis.net/def/crs/EPSG/0/3040 http://www.opengis.net/def/crs/EPSG/0/3041 http://www.opengis.net/def/crs/EPSG/0/3042 http://www.opengis.net/def/crs/EPSG/0/3043 http://www.opengis.net/def/crs/EPSG/0/3044 http://www.opengis.net/def/crs/EPSG/0/3045 http://www.opengis.net/def/crs/EPSG/0/3046 http://www.opengis.net/def/crs/EPSG/0/3047 http://www.opengis.net/def/crs/EPSG/0/3048 http://www.opengis.net/def/crs/EPSG/0/3049 http://www.opengis.net/def/crs/EPSG/0/3050 http://www.opengis.net/def/crs/EPSG/0/3051 http://www.opengis.net/def/crs/EPSG/0/5730 http://www.opengis.net/def/crs/EPSG/0/7409&quot;

(There seems to be an issue with 7409 as well currently https://github.com/etf-validator/etf-gmlgeox/issues/21, but I think, nonetheless, the process to add EPSG:7423 should be triggered as soon as possible.)

How to proceed in order to add them to the data specification or at least to this list https://github.com/inspire-eu-validation/data/blob/3.0rc3/reference-systems/spatial.md that is used for the INSPIRE Validator?

 

All the best

Johanna

**Comment by fabiovinci** [comment]
The INSPIRE MIG-T approved the change proposal during the [76th MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/76th+MIG-T+meeting+2023-11-30).
In the next step, the proposal will be moved to the MIG for the final endorsement.

**Comment by JohannaOtt** [comment]
> the proposal will be assessed by the MIG through a 2-week scrutiny period starting on 6/12/2023

@fabiovinci What was the outcome of this period?

**Comment by arantzaetxebarria** [comment]
Dear @JohannaOtt 

As you point out, the assessment period has ended and the proposal has been endorsed. The next step will be to introduce this new content into the INSPIRE Registry.

Regards

**Comment by arantzaetxebarria** [comment]
We would like to inform you that the proposal has been successfully published.

Regards
