### ISSUE TITLE
Why does EPSG 3006 not validate?

### ISSUE THREAD

**Issue by AndersEkmanLm** [INSPIRE-MIF/helpdesk-registry#79]
Currently, SWEREF 99 TM (EPSG 3006) does not pass validation. This poses a bit of a problem, since SWEREF 99 is the official reference frame for Sweden, and it would be practical to be able to use it in Swedish inspire services. As I understand it, other countries have similar problems with their official systems.

I am trying to understand why the validator does not allow EPSG 3006, and would appreciate some help.

EPSG 3006 fulfills all the requirements listed in 6.1.1.1 and 6.1.1.2 of the [TG DS Template](https://inspire.ec.europa.eu/file/1390/download?token=b3BlD8K2&usg=AOvVaw3vexhmHskK5Y2RIiDRtHrM). However, it is not included in table 2 (p. 24) of the same document. Judging from [this issues]( https://github.com/INSPIRE-MIF/helpdesk-validator/issues/294), this seems to be the trouble.

When I read the document, I don’t interpret table 2 to be meant as a complete list of *all* allowed systems (it only contains a small subsets of all the systems that would be allowed under 6.1.1.1 and 6.1.1.2). Is that a misreading on my part? Or is perhaps this just a technical limitation in the validator – it only allows systems in table 2, even though the technical guidelines would allow more?

Or in other words, what would it take to allow usage of EPSG 3006? An update to the validator, or an update of the technical guidelines, or perhaps something else?

**Comment by fabiovinci** [comment]
The INSPIRE MIG-T approved the change proposal during the [76th MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/76th+MIG-T+meeting+2023-11-30).
In the next step, the proposal will be moved to the MIG for the final endorsement.

**Comment by arantzaetxebarria** [comment]
We would like to inform you that the proposal has been successfully published.

Regards
