### ISSUE TITLE
Nomination request: JRC team member

### ISSUE THREAD

**Issue by andrea-perego** [INSPIRE-MIF/helpdesk-registry#8]
- Country: -
- Organisation: European Commission, Joint Research Centre (JRC)
- Contact name: Andrea Perego
- Contact e-mail: andrea.perego@ext.ec.europa.eu

**Comment by df-git** [comment]
Dear @andrea-perego 
You have been added as a member as requested.
Best regards,
Daniele on behalf of JRC INSPIRE Support team
