### ISSUE TITLE
Addition of EPSG:25832 and EPSG:25833 to INSPIRE-compliant CRSs

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/helpdesk-registry#80]
As discussed at the [64th MIG-T meeting](https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=644907982), Denmark would like to add EPSG:25832 and EPSG:25833 to the allowed list of coordinate reference systems in INSPIRE, as those are the same as the already allowed EPSG:3044 and EPSG:3045, only with the reverse axis order. The IR do not say anything about axis order. See also the [presentation](https://webgate.ec.europa.eu/fpfis/wikis/download/attachments/644907982/20210122%20CRS.pdf?version=1&modificationDate=1612168115370&api=v2).

At the 64th MIG-T meeting, a status was given by the Commission on the CRS registry. A timeline with reference to the relevant documents:

At the [8th meeting of the MIG](https://wayback.archive-it.org/12090/20201223113022/https://ies-svn.jrc.ec.europa.eu/projects/mig-p/wiki/8th_meeting_of_the_MIG), the document [Possible revision of Implementing Rules on data interoperability Status of change proposals](https://wayback.archive-it.org/12090/20201223113022/https://ies-svn.jrc.ec.europa.eu/attachments/download/2508/%5BDOC4rev%5D_Possible%20revision%20of%20IR%20on%20data%20interoperability_rev.pdf) was discussed, which contains a proposal from the MIG-T: 

> [...] to propose the setting up of a CRS registry containing all CRSs that are allowed in INSPIRE and to manage the proposal of additional CRS under the governance of the MIG. One key requirement for the endorsement of additional CRS would be the provision of unique transformation parameters to other well-known CRSs. [...]

In the [minutes of the 8th meeting](https://webgate.ec.europa.eu/fpfis/wikis/download/attachments/298660106/%5BDOC2%5D_Summary%208th%20MIG%20Brussels_draft.pdf?api=v2) it says that

> [...] the MIG supported the proposed solution to setup a Coordinate Reference System (CRS) registry and control body to manage the proposal of additional CRS under the governance of the MIG [...]

and

> The  MIG  supported  the  continuation  of  the  work  on  revising  the  interoperability  regulation. Based  on  the  discussion,  DG  ENV  and  JRC  will  now  prepare  a  concrete  proposal  for  the amendment of the legal act, a first draft of which will be presented and discussed in the MIG in November 2018.

In the [minutes](https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=596018902&preview=/596018902/606701738/%5BDOC2%5D_MIG12_Summary%2011th%20MIG_finaldraft.pdf) of the [11th MIG meeting](https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=452667656), it can be read that

> The Commission explained that the amendment to COMMISSION REGULATION 1089/2010 as regards interoperability  of  spatial data sets and services is delayed.  The amendment implements the changes agreed in the MIG as well as the corrigenda already agreed by the MIG in 2016. The Commission will try to push the procedure forward with the objective to present the amendment to the INSPIRE Committee as soon as possible.

So this issue is a placeholder to remember to propose the addition of EPSG:25832 and EPSG:25833 (and actually all CRSs with an EPSG code between 25828 and 25837) to the control body of the CRS registry as soon as that registry is in place.

**Comment by fabiovinci** [comment]
The INSPIRE MIG-T approved the change proposal during the [76th MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/76th+MIG-T+meeting+2023-11-30).
In the next step, the proposal will be moved to the MIG for the final endorsement.

**Comment by arantzaetxebarria** [comment]
We would like to inform you that the proposal has been successfully published.

Regards
