### ISSUE TITLE
Typing error in the list of 'Boorgatdoel'

### ISSUE THREAD

**Issue by ChandraAlgoe** [INSPIRE-MIF/helpdesk-registry#82]
https://inspire.ec.europa.eu/codelist/BoreholePurposeValue

Typing error in the list
please replace watervooziening by watervoorziening

![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/48786550/0f40f831-e29c-46b6-901c-3b22f31e8a1e)

**Comment by ChandraAlgoe** [comment]
Yes, the language affected is Nederlands

**Comment by arantzaetxebarria** [comment]
Dear  @ChandraAlgoe 

Thank you for your quick response, we will analyse the change proposal and will get back to you as soon as possible.
