### ISSUE TITLE
(Improvement) Wrong Registry Web page when Browser language is not an INSPIRE language

### ISSUE THREAD

**Issue by montsemarco** [INSPIRE-MIF/helpdesk-registry#83]
When accessing http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations with a Browser that is not configured in an INSPIRE language (for instance, Catalan), the web page is wrong. It seems that is trying to recover the text in catalan and it does not exist:

![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/1905272/d4eb1309-1a0f-4ed8-b570-300a815a9e8b)

Our metadata are implemented in a Geonetwork catalog, therefore, when pressing this link in the catalog it goes to that wrong Web page, making our catalog to have an incorrect behaviour.

![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/1905272/4bc78279-65a2-4281-9359-050bd7f5b53d)

This happens with all the metadata codelist. Examples: 
http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations
https://inspire.ec.europa.eu/metadata-codelist/OnLineDescriptionCode/accessPoint
http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory
http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoManagementService
http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/humanGeographicViewer

As an improvement, if the description in the registry does not exists in the language of the browser, at least return it in english, instead of returning a Web error message. 

Thanks and best regards

Montse

**Comment by jescriu** [comment]
Dear @montsemarco,
Thank you for opening this issue with the outcomes of the email discussion were had together with your colleague Marta, where we discovered this behaviour.
I will ask the contractor to accomodate this improvement in the next Re3gistry software release.
After that the enhancement will be implemented in the INSPIRE Registry in the next software update of this INSPIRE central component. 
In the meantime please assure your data providers are using INSPIRE Registry queries using e.g. English language. All of them are appropriately running.
All the best.

**Comment by arantzaetxebarria** [comment]
This ticket has been moved to [Re3gistry helpdesk](https://github.com/ec-jrc/re3gistry/issues) to implement a solution. Please, from now on refer to this ticket [#369](https://github.com/ec-jrc/re3gistry/issues/369) for tracking. 

Best regards

**Comment by montsemarco** [comment]
Sorry, but I cannot see the change. For instance, when I put this URL in my browser http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations I get exactly the same result

![image](https://github.com/INSPIRE-MIF/helpdesk-registry/assets/1905272/52a66e31-47d0-4798-812b-7b0a8b788d6a)

Thanks and best regards,
Montse

**Comment by arantzaetxebarria** [comment]
Dear @montsemarco 

Sorry, maybe I didn't make myself clear. 
The solution is present in version v2.5.3 of the Re3gistry software through ticket [#369](https://github.com/ec-jrc/re3gistry/issues/369). 
When the INSPIRE Registry instance is updated, the error will no longer occur.
If you have any questions, please do not hesitate to contact us.

Regards

**Comment by jescriu** [comment]
Dear @montsemarco,
The update of the software version of the INSPIRE Regustry will possibly take place in July (TBC).

**Comment by montsemarco** [comment]
Thanks for the explanation, I thought that it was already present.
Best regards,
