### ISSUE TITLE
Add maintenance frequency and spatial representation type code lists to INSPIRE Registry

### ISSUE THREAD

**Issue by andrea-perego** [INSPIRE-MIF/helpdesk-registry#9]
These two code lists are used in INSPIRE metadata and documented in the [INSPIRE Metadata TGs](https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139) (see sections C.7.1 and C.7.2, page 136).

They are also covered by the transformation rules defined in GeoDCAT-AP, where they are mapped to provisional and non dereferenceable URIs, as no URI registry is available for them.

The proposal is to add these two code lists to the INSPIRE Registry, under the metadata code lists register:

http://inspire.ec.europa.eu/metadata-codelist

Detailed proposal below. Codes, labels, and definitions are from ISO 19115:2003.

### Code list

|Field|Value|
|----|----|
|ID|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency|
|Label|Maintenance frequency|
|Definition|Frequency with which modifications and deletions are made to the data after it is first produced.|
|Governance level|eu-technical|

### Code list values

|ID|Label|Definition|
|----|----|----|
|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency/continual|Continual|Data is repeatedly and frequently updated.|
|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency/daily|Daily|Data is updated each day.|
|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency/weekly|Weekly|Data is updated on a weekly basis.|
|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency/fortnightly|Fortnightly|Data is updated every two weeks.|
|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency/monthly|Monthly|Data is updated each month.|
|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency/quarterly|Quarterly|Data is updated every three months.|
|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency/biannually|Biannually|Data is updated twice each year.|
|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency/annually|Annually|Data is updated every year.|
|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency/asNeeded|As needed|Data is updated as deemed necessary.|
|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency/irregular|Irregular|Data is updated in intervals that are uneven in duration.|
|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency/notPlanned|Not planned|There are no plans to update the data.|
|http://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency/unknown|Unknown|Frequency of maintenance for the data is not known.|

### Code list

|Field|Value|
|----|----|
|ID|http://inspire.ec.europa.eu/metadata-codelist/SpatialRepresentationType|
|Label|Spatial representation type|
|Definition|Method used to represent geographic information in the dataset.|
|Governance level|eu-technical|

### Code list values (codes, labels and definitions are from ISO 19115:2003):

|ID|Label|Definition|
|----|----|----|
|http://inspire.ec.europa.eu/metadata-codelist/SpatialRepresentationType/vector|Vector|Vector data is used to represent geographic data.|
|http://inspire.ec.europa.eu/metadata-codelist/SpatialRepresentationType/grid|Grid|Grid data is used to represent geographic data.|
|http://inspire.ec.europa.eu/metadata-codelist/SpatialRepresentationType/textTable|Text table|Textual or tabular data is used to represent geographic data.|
|http://inspire.ec.europa.eu/metadata-codelist/SpatialRepresentationType/tin|TIN|Triangulated irregular network.|
|http://inspire.ec.europa.eu/metadata-codelist/SpatialRepresentationType/stereoModel|Stereo model|Three-dimensional view formed by the intersecting homologous rays of an overlapping pair of images.|
|http://inspire.ec.europa.eu/metadata-codelist/SpatialRepresentationType/video|Video|Scene from a video recording.|

**Comment by hernlor** [comment]
Dear @andrea-perego, thank you for your request.

The proposal is now and for the next two weeks under the scrutiny of the control body.
If passed this time there are no comments or objections. We will proceed to its implementation.

Kind regards, 
INSPIRE Registry team.

**Comment by hernlor** [comment]
Dear Andrea, 

After the scrutiny period, the proposed codelists have been accepted and added to the metadata codelist register.

You can find them at:

- https://inspire.ec.europa.eu/metadata-codelist/SpatialRepresentationType
- https://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency

Kind regards, 
The INSPIRE registry team
