### ISSUE TITLE
New definition for DesignationValue - Changes from 1089 amendment

### ISSUE THREAD

**Issue by fabiovinci** [INSPIRE-MIF/helpdesk-registry#90]
**Motivation**: The IR amendment [Commission Regulation (EU) 2023/2431 of 24 October 2023 amending Regulation (EU) No 1089/2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services](https://eur-lex.europa.eu/eli/reg/2023/2431/oj) changed the definition of the DesignationValue codelist of the [Protected Sites](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/data/ps) data theme.

**Proposed change**: Change the definition of the DesignationValue codelist. The new definition is: "Classification and designation types under different schemes."

**Change type**: Clarification

**URI**: https://inspire.ec.europa.eu/codelist/DesignationValue

**Related TG issue**: https://github.com/INSPIRE-MIF/technical-guidelines/issues/129

**Comment by arantzaetxebarria** [comment]
The description of the codelist https://inspire.ec.europa.eu/codelist/DesignationValue has been changed and published correctly
