### ISSUE TITLE
Add CRS EPSG:3794 for Slovenia

### ISSUE THREAD

**Issue by UrsaKA** [INSPIRE-MIF/helpdesk-registry#92]
We would like to propose adding the CRS for the Slovenian national grid to the list of accepted CRS. Slovenia uses **EPSG:3794**
Currently data with this CRS cannot be validated.

We would also like to propose adding **EPSG:4326** which is very commonly used.

Where can we start the proposal process? Is this issue enough or are additional steps needed?

**Comment by arantzaetxebarria** [comment]
In the MIWP Action 2.3.1 MIG-T Sub-group Meeting on 06/05/2024, it was agreed to bring this proposal for endorsement in the [78 MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/78th+MIG-T+meeting+2024-05-17).

Add the CRS **EPSG:3794** for the Slovenian national grid to the list of accepted CRS.

**Comment by arantzaetxebarria** [comment]
The INSPIRE MIG-T approved the change proposal during the [78 MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/78th+MIG-T+meeting+2024-05-17)

**Comment by arantzaetxebarria** [comment]
We want to inform you that the proposal has been successfully published.
https://inspire.ec.europa.eu/crs/3794

Regards
