### ISSUE TITLE
Type in the definition of the LimitationsOnPublicAccess/noLimitations code list item

### ISSUE THREAD

**Issue by jescriu** [INSPIRE-MIF/helpdesk-registry#97]
On behalf of Jeroen Ticheler, who spotted this issue.

A typo has been noticed in one of the Dutch code list entries in the INSPIRE registry here: https://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations

The Definition says “Geen beperkinge.” but this should be “Geen beperkingen.”

JRC, as a submitting organisation, gives support to this change proposal.

- the URI of the register/reference code: https://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations
- the rationale or motivation behind this proposal: typo in the definition and inconsistency with the item itself and its (correct) label
- the proposed change: change the defintion from “Geen beperkinge.” to “Geen beperkingen.”
- the change type: clarification

We request to directly include it in the 2024.2 INSPIRE Registry release, since it is just the correction of a typo.

**Comment by arantzaetxebarria** [comment]
We want to inform you that the proposal has been successfully published.

https://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations

Regards
